### PR TITLE
Add authorization for the DELETE endpoint

### PR DESCRIPTION
**Pull request by sswguo**

### CODE REVIEW

**Comment by sswguo** [comment]
@ruhan1 I forgot to merge the previous PR and mixed the promoteEventConsumer here too, but both are small, please help to review. Let's see what you need for response after the cleanup and do we need to add a unique ID for the event ? then you can check the response based on it.

**Comment by ruhan1** [comment]
This looks good. Only thing is we use different channel name. I updated promote side to be 'promote-event-in' as well. The ack is sent after the deletion, so this is in line with promote design.

**Comment by ruhan1** [comment]
feel free to close the jira.

**Comment by sswguo** [comment]
> This looks good. Only thing is we use different channel name. I updated promote side to be 'promote-event-in' as well. The ack is sent after the deletion, so this is in line with promote design.

you don't need to update that channel name, it's used inside metadata service as the mapping between config and codebase, we just need to make sure we use the same topic. ;-)

**Pull request merged**
